//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISkillProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseUser
    {
        public int CourseUser1 { get; set; }
        public string CourseName { get; set; }
        public string Image { get; set; }
        public int CourseId { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Course Course { get; set; }
    }
}
